# Workflow to build and deploy to your GitHub Pages repo.

# Edit your project details here.
# Remember to add API_TOKEN_GITHUB in repo Settings > Secrets as well!
name: Github Pages Astro CI

on:
  # Allows you to run this workflow manually from the Actions tab.
  # Triggers the workflow on push and pull request events but only for the main branch
  workflow_dispatch:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  schedule:
    - cron: "30 21 * * *" # every day at 21:30 UTC (= 22:30 CET)

jobs:
  combined-workflow:

    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build frontend
        working-directory: frontend/
        env:
          KB_EMAIL: ${{ secrets.KB_EMAIL }}
          KB_PW: ${{ secrets.KB_PW }}
          KB_LEAGUE_ID: ${{ secrets.KB_LEAGUE_ID }}
        run: |
          ls -la
          npm ci
          CI=false && npm run build --if-present
          touch ./dist/.nojekyll

      - name: Deploy frontend
        working-directory: frontend/
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: ${{ github.repository }}
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
