name: Github Pages Astro CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "30 21 * * *" # every day at 21:30 UTC (= 22:30 CET)

jobs:
  combined-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies with npm
      - name: Install dependencies
        run: npm ci

      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build frontend
        working-directory: frontend/
        env:
          KB_EMAIL: ${{ secrets.KB_EMAIL }}
          KB_PW: ${{ secrets.KB_PW }}
          KB_LEAGUE_ID: ${{ secrets.KB_LEAGUE_ID }}
        run: |
          npm run build
          touch ./dist/.nojekyll

      # Push to your pages repo
      - name: Deploy frontend
        uses: cpina/github-action-push-to-another-repository@main
        env:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'github-actions[bot]'
          destination-repository-name: ${{ github.repository }}
          user-email: 'github-actions[bot]@users.noreply.github.com'
          user-name: 'github-actions[bot]'
          commit-message: Deploy ORIGIN_COMMIT
          target-branch: gh-pages
