name: Github Pages Astro CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "30 21 * * *" # every day at 21:30 UTC (= 22:30 CET)

jobs:
  combined-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build frontend
        working-directory: frontend/
        env:
          KB_EMAIL: ${{ secrets.KB_EMAIL }}
          KB_PW: ${{ secrets.KB_PW }}
          KB_LEAGUE_ID: ${{ secrets.KB_LEAGUE_ID }}
        run: |
          npm ci
          CI=false && npm run build --if-present
          touch ./dist/.nojekyll

      - name: Deploy frontend
        working-directory: frontend/
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: ${{ github.repository }}
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
